import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import Container from "@/components/layout/Container";

const firaSans = Fira_Sans({
  weight: "400",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Wonderkid Portfolio",
  description: "Generated by NextJS + Three.Js + ♡",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.className} h-screen bg-customPrimaryBg text-customPrimaryText`}
      >
        {children}
      </body>
    </html>
  );
}
